### ISSUE TITLE
Support compilers as old as g++-4.9

### ISSUE THREAD

**Issue by springmeyer** [mapbox/hpp-skel#37]
We should maintain support for compilers as old as g++-4.9 to set up users of this project for success in keeping this support and not regression without knowing.

The code in hpp-skel does not need to change for this. What needs to happen is to add a travis matrix that tests on g++-4.9 like https://github.com/mapbox/geometry.hpp/commit/2c71de6f1f92b9cb81defc3499ea07ba1c43c834#diff-354f30a63fb0907d4ad57269548329e3R7

```
    - os: linux
      sudo: false
      env: CXX=g++-4.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-4.9' ]
```

And then we need to make sure it stays passing, which should be easy since the code in hpp-skel is simple.

/cc @brunoabinader @tmpsantos
